# Build stage
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /source

COPY . .
RUN dotnet publish Gymmetry.Functions/Gymmetry.Functions.csproj \
    -c Release \
    -o /app/publish

# Final stage: Azure Functions Runtime
FROM mcr.microsoft.com/azure-functions/dotnet-isolated:4.0

WORKDIR /home/site/wwwroot
COPY --from=build /app/publish .

# No necesitas instalar func tools aquí si usas la imagen base de Azure Functions
